spring.application.name=GraphqlAuthApplication
spring.graphql.websocket.path=/graphql
spring.graphql.graphiql.enabled=true
server.port=8081

# JWT Secret Key
#openssl rand -base64 32
jwt.secret= T2s8f9K2mL0xYpQwR6zA1vC3eD5gH7jK9lMnOpQrStU=

# 15 Minutes Expiration
#1000ms * 60 sec * 15 min
jwt.expiration=900000
